# Generated by Django 5.2.11 on 2026-02-06 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='availability',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mentor',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='preferred_formats',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mentor',
            name='response_time_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='MenteeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.JSONField(blank=True, default=list)),
                ('free_text', models.TextField(blank=True)),
                ('preferred_times', models.JSONField(blank=True, default=list)),
                ('preferred_format', models.CharField(blank=True, choices=[('1:1', '1:1'), ('Group', 'Group'), ('Drop-in', 'Drop-in'), ('Workshop', 'Workshop')], max_length=20)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('access_needs', models.TextField(blank=True)),
                ('safety_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.mentee')),
            ],
        ),
        migrations.CreateModel(
            name='MatchRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('explanation', models.TextField(blank=True)),
                ('matched_topics', models.JSONField(blank=True, default=list)),
                ('availability_overlap', models.JSONField(blank=True, default=list)),
                ('response_time_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rating_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='suggested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.mentor')),
                ('mentee_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.menteerequest')),
            ],
        ),
    ]
