# Generated by Django 5.2.11 on 2026-02-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mentor_availability_mentor_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrecommendation',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='matchrecommendation',
            name='prompt_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='matchrecommendation',
            name='response_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='matchrecommendation',
            name='source',
            field=models.CharField(choices=[('seed', 'Seed'), ('openai', 'OpenAI'), ('manual', 'Manual')], default='seed', max_length=20),
        ),
    ]
