# Generated by Django 5.2.11 on 2026-02-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_matchrecommendation_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteerequest',
            name='comfort_level',
            field=models.CharField(blank=True, choices=[('Very Uncomfortable', 'Very Uncomfortable'), ('Somewhat Uncomfortable', 'Somewhat Uncomfortable'), ('Neutral', 'Neutral'), ('Comfortable', 'Comfortable'), ('Very Comfortable', 'Very Comfortable')], max_length=30),
        ),
        migrations.AddField(
            model_name='menteerequest',
            name='feeling',
            field=models.CharField(blank=True, choices=[('Burnt Out', 'Burnt Out'), ('Anxious', 'Anxious'), ('Confused', 'Confused'), ('Lonely', 'Lonely'), ('Hopeful', 'Hopeful'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='menteerequest',
            name='feeling_cause',
            field=models.CharField(blank=True, choices=[('Exam Pressure', 'Exam Pressure'), ('Parent Expectations', 'Parent Expectations'), ('Friend Issues', 'Friend Issues'), ('Future Anxiety (Career/College)', 'Future Anxiety (Career/College)'), ('Concentration Struggles', 'Concentration Struggles'), ('Study Struggles', 'Study Struggles'), ('Others', 'Others')], max_length=80),
        ),
        migrations.AddField(
            model_name='menteerequest',
            name='support_type',
            field=models.CharField(blank=True, choices=[('Someone to Listen', 'Someone to Listen'), ('Study Guidance / Tips', 'Study Guidance / Tips'), ('Motivation', 'Motivation'), ('Stress Relief Strategies', 'Stress Relief Strategies'), ('Life Advice / Perspective', 'Life Advice / Perspective'), ("I'm Not Sure", "I'm Not Sure")], max_length=80),
        ),
    ]
