# Generated by Django 5.2.11 on 2026-02-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_menteerequest_comfort_level_menteerequest_feeling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='city_state',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='mentee',
            name='timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='menteerequest',
            name='allow_auto_match',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menteerequest',
            name='safety_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menteerequest',
            name='session_mode',
            field=models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person')], default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchrecommendation',
            name='source',
            field=models.CharField(choices=[('seed', 'Seed'), ('rules', 'Rules'), ('openai', 'OpenAI'), ('manual', 'Manual')], default='seed', max_length=20),
        ),
    ]
