# Generated by Django 5.2.11 on 2026-02-09 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mentee_city_state_mentee_timezone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('lesson_outline', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('estimated_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MentorContactVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('email_otp_hash', models.CharField(blank=True, max_length=128)),
                ('email_otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('email_otp_attempts', models.PositiveSmallIntegerField(default=0)),
                ('phone_verified', models.BooleanField(default=False)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('phone_otp_hash', models.CharField(blank=True, max_length=128)),
                ('phone_otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('phone_otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('phone_otp_attempts', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_verification', to='core.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='MentorIdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_front', models.FileField(blank=True, null=True, upload_to='mentor_verification/aadhaar/front/')),
                ('aadhaar_back', models.FileField(blank=True, null=True, upload_to='mentor_verification/aadhaar/back/')),
                ('passport_or_license', models.FileField(blank=True, null=True, upload_to='mentor_verification/id/')),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity_verification', to='core.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='MentorOnboardingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='completed', max_length=20)),
                ('identity_status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('contact_status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('training_status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('final_approval_status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('current_status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='in_review', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_status', to='core.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='MentorTrainingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_progress', to='core.mentor')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_progress', to='core.trainingmodule')),
            ],
            options={
                'unique_together': {('mentor', 'module')},
            },
        ),
    ]
