# Generated by Django 5.2.11 on 2026-02-09 06:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_trainingmodule_mentorcontactverification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenteePreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comfort_level', models.CharField(blank=True, max_length=30)),
                ('preferred_session_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('preferred_mentor_types', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='core.mentee')),
            ],
        ),
        migrations.CreateModel(
            name='MentorAvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='core.mentor')),
            ],
            options={
                'ordering': ['start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=40, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=150)),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='mentor_profiles/photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('sessions_completed', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='MentorWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pending_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_claimed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_donated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='core.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='ParentConsentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_mobile', models.CharField(blank=True, max_length=20)),
                ('otp_hash', models.CharField(blank=True, max_length=128)),
                ('otp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('otp_attempts', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('mentee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_consent_verification', to='core.mentee')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=45)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person')], default='online', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('no_show', 'No Show')], default='requested', max_length=20)),
                ('topic_tags', models.JSONField(blank=True, default=list)),
                ('mentee_notes', models.TextField(blank=True)),
                ('mentor_notes', models.TextField(blank=True)),
                ('join_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.mentoravailabilityslot')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.mentee')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.mentor')),
            ],
            options={
                'ordering': ['-scheduled_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayoutTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('session_claim', 'Session Claim'), ('bank_payout', 'Bank Payout'), ('adjustment', 'Adjustment')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_transactions', to='core.mentor')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_transactions', to='core.session')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DonationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cause', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_transactions', to='core.mentor')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donation_transaction', to='core.session')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SessionDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('claim', 'Claim Payment'), ('donate', 'Donate Session'), ('report', 'Report Issue')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_dispositions', to='core.mentor')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposition', to='core.session')),
            ],
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('topics_discussed', models.JSONField(blank=True, default=list)),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.session')),
            ],
        ),
        migrations.CreateModel(
            name='SessionIssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('technical_issue', 'Technical Issue'), ('mentee_no_show', 'Mentee No-show'), ('safety_concern', 'Safety Concern'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='core.mentor')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue_report', to='core.session')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
