# Generated by Django 5.2.11 on 2026-02-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_menteepreferences_mentoravailabilityslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='avatar',
            field=models.URLField(blank=True),
        ),
    ]
