# Generated by Django 5.2.11 on 2026-02-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_donationtransaction_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentoronboardingstatus",
            name="final_rejection_reason",
            field=models.TextField(blank=True),
        ),
    ]
