# Generated by Django 5.2.11 on 2026-02-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_mentoronboardingstatus_final_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentee",
            name="avatar",
            field=models.FileField(blank=True, null=True, upload_to="mentee/avatar/"),
        ),
    ]
