# Generated by Django 5.2.11 on 2026-02-16 12:26

from django.db import migrations, models


def seed_first_module_video_urls(apps, schema_editor):
    TrainingModule = apps.get_model('core', 'TrainingModule')
    first_modules = TrainingModule.objects.filter(order=1)
    for module in first_modules:
        updated_fields = []
        if not (module.video_url_1 or "").strip():
            module.video_url_1 = "https://youtu.be/7wUCyjiyXdg"
            updated_fields.append("video_url_1")
        if not (module.video_url_2 or "").strip():
            module.video_url_2 = "https://youtu.be/f_wprGcziso"
            updated_fields.append("video_url_2")
        if updated_fields:
            module.save(update_fields=updated_fields)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_mentee_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodule',
            name='video_url_1',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='video_url_2',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.RunPython(seed_first_module_video_urls, noop_reverse),
    ]
