# Generated by Django 5.2.11 on 2026-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_trainingmodule_video_url_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentee",
            name="grade",
            field=models.CharField(
                choices=[
                    ("10th Grade", "10th Grade"),
                    ("11th Grade", "11th Grade"),
                    ("12th Grade", "12th Grade"),
                ],
                max_length=20,
            ),
        ),
    ]
