# Generated by Django 5.2.11 on 2026-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_mentee_grade_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentee",
            name="gender",
            field=models.CharField(
                choices=[("Female", "Female"), ("Male", "Male")],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="mentor",
            name="gender",
            field=models.CharField(
                choices=[("Female", "Female"), ("Male", "Male")],
                max_length=32,
            ),
        ),
    ]
