# Generated by Django 5.2.11 on 2026-02-20 11:53

from django.db import migrations, models


def sync_current_status_to_approved(apps, schema_editor):
    MentorOnboardingStatus = apps.get_model('core', 'MentorOnboardingStatus')
    completed_like = ['completed', 'verified']
    MentorOnboardingStatus.objects.filter(
        application_status__in=completed_like,
        identity_status__in=completed_like,
    ).exclude(current_status='approved').update(current_status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_adminaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentoronboardingstatus',
            name='final_approval_status',
        ),
        migrations.AlterField(
            model_name='mentoronboardingstatus',
            name='application_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='mentoronboardingstatus',
            name='contact_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='mentoronboardingstatus',
            name='current_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='in_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='mentoronboardingstatus',
            name='identity_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='mentoronboardingstatus',
            name='training_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.RunPython(sync_current_status_to_approved, migrations.RunPython.noop),
    ]
