# Generated by Django 5.2.11 on 2026-02-20 11:57

from django.db import migrations, models


def normalize_onboarding_status_values(apps, schema_editor):
    MentorOnboardingStatus = apps.get_model('core', 'MentorOnboardingStatus')

    # Normalize legacy values after the temporary "approved" status.
    for field_name in [
        'application_status',
        'identity_status',
        'contact_status',
        'training_status',
        'current_status',
    ]:
        MentorOnboardingStatus.objects.filter(**{field_name: 'approved'}).update(
            **{field_name: 'completed'}
        )
        MentorOnboardingStatus.objects.filter(**{field_name: 'verified'}).update(
            **{field_name: 'completed'}
        )

    # Product rule: completed when application + identity are completed.
    MentorOnboardingStatus.objects.filter(
        application_status='completed',
        identity_status='completed',
    ).exclude(current_status='completed').update(current_status='completed')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_mentoronboardingstatus_final_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoronboardingstatus',
            name='application_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='mentoronboardingstatus',
            name='contact_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='mentoronboardingstatus',
            name='current_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='in_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='mentoronboardingstatus',
            name='identity_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='mentoronboardingstatus',
            name='training_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.RunPython(normalize_onboarding_status_values, migrations.RunPython.noop),
    ]
