# Generated by Django 5.2.11 on 2026-02-24 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_mentoronboardingstatus_application_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAbuseIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_role', models.CharField(choices=[('mentee', 'Mentee'), ('mentor', 'Mentor'), ('admin', 'Admin'), ('system', 'System'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('transcript_snippet', models.TextField(blank=True)),
                ('matched_terms', models.JSONField(blank=True, default=list)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('flagged_mentee_snapshot', models.JSONField(blank=True, default=dict)),
                ('detection_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_incidents', to='core.session')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SessionMeetingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('mentee', 'Mentee'), ('mentor', 'Mentor'), ('admin', 'Admin'), ('system', 'System'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('signal_type', models.CharField(choices=[('offer', 'Offer'), ('answer', 'Answer'), ('ice', 'ICE Candidate'), ('bye', 'Call Ended')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_signals', to='core.session')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SessionRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('recording', 'Recording'), ('stopped', 'Stopped'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], default='not_started', max_length=20)),
                ('recording_url', models.URLField(blank=True)),
                ('storage_key', models.CharField(blank=True, max_length=255)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='core.session')),
            ],
        ),
    ]
