# Generated by Django 5.2.11 on 2026-02-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_sessionabuseincident_sessionmeetingsignal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrecording',
            name='recording_file',
            field=models.FileField(blank=True, null=True, upload_to='session_recordings/'),
        ),
    ]
