# Generated by Django 5.2.11 on 2026-02-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_sessionrecording_recording_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='mentor_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
