# Generated by Django 5.2.11 on 2026-03-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_session_mentor_joined_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="mentee_joined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
