# Generated by Django 5.2.11 on 2026-03-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_mentoridentityverification_document_review_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionabuseincident',
            name='detection_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='sessionabuseincident',
            name='detection_source',
            field=models.CharField(choices=[('transcript', 'Transcript'), ('manual_report', 'Manual Report'), ('client_signal', 'Client Signal'), ('ai_vision', 'AI Vision')], default='manual_report', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionabuseincident',
            name='event_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionabuseincident',
            name='evidence_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sessionabuseincident',
            name='incident_type',
            field=models.CharField(choices=[('verbal_abuse', 'Verbal Abuse'), ('inappropriate_gesture', 'Inappropriate Gesture'), ('inappropriate_attire', 'Inappropriate Attire'), ('sexual_content', 'Sexual Content'), ('harassment', 'Harassment'), ('unsafe_environment', 'Unsafe Environment'), ('unknown', 'Unknown')], default='unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='sessionabuseincident',
            name='recommended_action',
            field=models.CharField(choices=[('none', 'None'), ('warn', 'Warn'), ('escalate_review', 'Escalate Review'), ('terminate_session', 'Terminate Session')], default='none', max_length=20),
        ),
    ]
