# Generated by Django 5.2.11 on 2026-03-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_sessionabuseincident_detection_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='mentee_monitoring_words',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='session',
            name='mentor_monitoring_words',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
