# Generated by Django 5.2.11 on 2026-03-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_session_mentee_monitoring_words_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmeetingsignal',
            name='signal_type',
            field=models.CharField(choices=[('offer', 'Offer'), ('answer', 'Answer'), ('ice', 'ICE Candidate'), ('bye', 'Call Ended'), ('media_state', 'Media State'), ('safety_alert', 'Safety Alert'), ('transcript', 'Transcript'), ('transcript_bundle', 'Transcript Bundle'), ('mentor_transcript', 'Mentor Transcript'), ('mentee_transcript', 'Mentee Transcript'), ('mentor_bundle', 'Mentor Transcript Bundle'), ('mentee_bundle', 'Mentee Transcript Bundle')], max_length=20),
        ),
    ]
