# Generated by Django 5.2.11 on 2026-03-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_sessionmeetingsignal_signal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
