# Generated by Django 5.2.11 on 2026-03-27 11:44

import django.db.models.deletion
from django.db import migrations, models


def seed_volunteer_events(apps, schema_editor):
    VolunteerEvent = apps.get_model("core", "VolunteerEvent")
    rows = [
        {
            "title": "Care Day at Chennai Cancer Institute",
            "stream": "Healthcare Support",
            "image": "https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?auto=format&fit=crop&w=1200&q=80",
            "description": "Teen groups will host games, music, and support circles with patients and families to create a joyful weekend at the institute.",
            "status": "upcoming",
            "date": "2026-03-28",
            "time": "10:00 AM - 2:00 PM",
            "location": "Chennai Cancer Institute, Chennai",
            "organizer": "Bond Room Teen Circle - Team A",
            "seats": 40,
            "is_active": True,
        },
        {
            "title": "Marina Coast Marine Cleaning Drive",
            "stream": "Marine Environment",
            "image": "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=1200&q=80",
            "description": "A weekend shoreline cleanup focused on plastic collection, waste sorting, and awareness posters led by volunteer youth teams.",
            "status": "upcoming",
            "date": "2026-04-04",
            "time": "6:30 AM - 10:30 AM",
            "location": "Marina Beach, Chennai",
            "organizer": "Blue Shore Youth Squad",
            "seats": 60,
            "is_active": True,
        },
        {
            "title": "Old Age Home Story & Activity Circle",
            "stream": "Elder Care",
            "image": "https://images.unsplash.com/photo-1516307365426-bea591f05011?auto=format&fit=crop&w=1200&q=80",
            "description": "Volunteers spend quality time with elders through storytelling, board games, music, and guided memory-sharing activities.",
            "status": "upcoming",
            "date": "2026-04-11",
            "time": "4:00 PM - 7:00 PM",
            "location": "Anbu Old Age Home, Chennai",
            "organizer": "Bond Room Weekend Connect",
            "seats": 35,
            "is_active": True,
        },
        {
            "title": "Community Tree Planting Sprint",
            "stream": "Community Action",
            "image": "https://images.unsplash.com/photo-1464039397811-476f652a343b?auto=format&fit=crop&w=1200&q=80",
            "description": "Teen volunteers plant native saplings, map care schedules, and partner with local residents for 90-day survival tracking.",
            "status": "upcoming",
            "date": "2026-04-19",
            "time": "7:30 AM - 11:30 AM",
            "location": "Velachery Community Ground, Chennai",
            "organizer": "Green Teens Collective",
            "seats": 50,
            "is_active": True,
        },
        {
            "title": "Community Library Setup Drive",
            "stream": "Education Support",
            "image": "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1200&q=80",
            "summary": "Volunteers organized donated books, set up reading corners, and launched weekend reading circles for students.",
            "status": "completed",
            "completed_on": "2026-02-08",
            "location": "Kodambakkam Community Hall, Chennai",
            "impact": "320 books cataloged",
            "is_active": True,
        },
        {
            "title": "Neighborhood Lake Restoration Campaign",
            "stream": "Environment",
            "image": "https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80",
            "summary": "Students and mentors cleaned walking tracks, removed plastic waste, and installed awareness boards around the lake.",
            "status": "completed",
            "completed_on": "2026-01-19",
            "location": "Velachery Lake Zone, Chennai",
            "impact": "1.8 tons waste removed",
            "is_active": True,
        },
        {
            "title": "Public Health Checkup Assist Day",
            "stream": "Healthcare Support",
            "image": "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=1200&q=80",
            "summary": "Volunteer teams coordinated patient queues, assisted registration desks, and supported elder citizens during screening.",
            "status": "completed",
            "completed_on": "2025-12-21",
            "location": "Anna Nagar PHC, Chennai",
            "impact": "540 residents supported",
            "is_active": True,
        },
    ]
    for row in rows:
        VolunteerEvent.objects.get_or_create(
            title=row["title"],
            defaults=row,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_mentee_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('stream', models.CharField(blank=True, max_length=120)),
                ('image', models.URLField(blank=True, max_length=700)),
                ('description', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=120)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=220)),
                ('organizer', models.CharField(blank=True, max_length=220)),
                ('seats', models.PositiveIntegerField(default=0)),
                ('impact', models.CharField(blank=True, max_length=220)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['status', 'date', '-completed_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerEventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by_role', models.CharField(choices=[('mentee', 'Mentee'), ('mentor', 'Mentor'), ('admin', 'Admin')], default='mentee', max_length=20)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('team_name', models.CharField(max_length=150)),
                ('school_or_college', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('postal_code', models.CharField(max_length=20)),
                ('preferred_role', models.CharField(blank=True, max_length=120)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_registrations', to='core.mentee')),
                ('volunteer_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.volunteerevent')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('volunteer_event', 'mentee'), name='uniq_volunteer_event_registration_per_mentee')],
            },
        ),
        migrations.RunPython(seed_volunteer_events, migrations.RunPython.noop),
    ]
