from django.db import migrations


def seed_more_volunteer_events(apps, schema_editor):
    VolunteerEvent = apps.get_model("core", "VolunteerEvent")

    rows = [
        {
            "title": "City Blood Donation Support Camp",
            "stream": "Healthcare Support",
            "image": "https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=1200&q=80",
            "description": "Students assist donor registration desks, queue management, and awareness counters at the city camp.",
            "status": "upcoming",
            "date": "2026-05-03",
            "time": "9:00 AM - 1:00 PM",
            "location": "Government Medical College Hall, Chennai",
            "organizer": "Bond Room Health Volunteers",
            "seats": 45,
            "is_active": True,
        },
        {
            "title": "Weekend School Painting & Repair Drive",
            "stream": "Community Action",
            "image": "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=80",
            "description": "Volunteer teams repaint classrooms, clean campus areas, and restore student activity boards.",
            "status": "upcoming",
            "date": "2026-05-10",
            "time": "8:00 AM - 12:30 PM",
            "location": "Corporation Middle School, Chennai",
            "organizer": "Youth Community Builders",
            "seats": 55,
            "is_active": True,
        },
        {
            "title": "Public Park Weekend Clean Sweep",
            "stream": "Environment",
            "image": "https://images.unsplash.com/photo-1472141521881-95d0e87e2e39?auto=format&fit=crop&w=1200&q=80",
            "description": "Cleanup and segregation activity across walking trails with awareness sessions for families.",
            "status": "upcoming",
            "date": "2026-05-17",
            "time": "6:30 AM - 10:00 AM",
            "location": "Semmozhi Poonga, Chennai",
            "organizer": "Green Teens Circle",
            "seats": 70,
            "is_active": True,
        },
        {
            "title": "Community Nutrition Awareness Walk",
            "stream": "Healthcare Support",
            "image": "https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=1200&q=80",
            "description": "Volunteers conduct awareness stalls and distribute nutrition guide cards in neighborhood clusters.",
            "status": "upcoming",
            "date": "2026-05-24",
            "time": "7:00 AM - 11:00 AM",
            "location": "Anna Nagar Tower Park, Chennai",
            "organizer": "Bond Room Wellness Team",
            "seats": 50,
            "is_active": True,
        },
        {
            "title": "Senior Citizen Digital Help Desk",
            "stream": "Elder Care",
            "image": "https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1200&q=80",
            "description": "Teen volunteers help senior citizens with smartphone basics, UPI safety, and essential app navigation.",
            "status": "upcoming",
            "date": "2026-06-07",
            "time": "3:00 PM - 6:30 PM",
            "location": "Community Centre, Mylapore",
            "organizer": "Digital Saathi Youth Group",
            "seats": 36,
            "is_active": True,
        },
        {
            "title": "Science Fair Volunteer Coordination",
            "stream": "Education Support",
            "image": "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80",
            "description": "Volunteers support registration counters, student booths, and guest guidance at inter-school science fair.",
            "status": "upcoming",
            "date": "2026-06-14",
            "time": "9:30 AM - 4:00 PM",
            "location": "YMCA Grounds, Chennai",
            "organizer": "Student Innovation Network",
            "seats": 80,
            "is_active": True,
        },
        {
            "title": "Neighborhood Rainwater Harvesting Awareness",
            "stream": "Environment",
            "image": "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80",
            "description": "Street-level campaign on rooftop water harvesting methods, maintenance and summer preparedness.",
            "status": "upcoming",
            "date": "2026-06-21",
            "time": "7:00 AM - 10:30 AM",
            "location": "Adyar Residential Zone, Chennai",
            "organizer": "Water Wise Volunteers",
            "seats": 42,
            "is_active": True,
        },
        {
            "title": "Community Sports Day Support",
            "stream": "Community Action",
            "image": "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&q=80",
            "description": "Volunteer crew manages participant check-ins, field logistics, hydration stations, and result boards.",
            "status": "upcoming",
            "date": "2026-06-28",
            "time": "6:00 AM - 12:00 PM",
            "location": "Nehru Stadium, Chennai",
            "organizer": "Bond Room Sports Connect",
            "seats": 65,
            "is_active": True,
        },
        {
            "title": "Orphanage Learning Support Weekend",
            "stream": "Education Support",
            "image": "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1200&q=80",
            "description": "Volunteers conduct spoken-English games, math puzzles, and creative storytelling for children.",
            "status": "upcoming",
            "date": "2026-07-05",
            "time": "2:00 PM - 6:00 PM",
            "location": "Children Care Home, Chennai",
            "organizer": "Bright Minds Volunteer Club",
            "seats": 34,
            "is_active": True,
        },
        {
            "title": "Urban Tree Care Follow-up Day",
            "stream": "Environment",
            "image": "https://images.unsplash.com/photo-1492496913980-501348b61469?auto=format&fit=crop&w=1200&q=80",
            "description": "Teams revisit planted saplings for mulching, staking and survival audit updates.",
            "status": "upcoming",
            "date": "2026-07-12",
            "time": "7:00 AM - 11:00 AM",
            "location": "Velachery, Chennai",
            "organizer": "Green Teens Collective",
            "seats": 48,
            "is_active": True,
        },
        {
            "title": "Street Animal Care Outreach",
            "stream": "Community Action",
            "image": "https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=1200&q=80",
            "description": "Volunteer support for feeding points, adoption awareness and vaccination camp coordination.",
            "status": "upcoming",
            "date": "2026-07-19",
            "time": "6:30 AM - 10:30 AM",
            "location": "Besant Nagar, Chennai",
            "organizer": "Compassion Crew",
            "seats": 38,
            "is_active": True,
        },
        {
            "title": "Night Shelter Blanket Distribution",
            "stream": "Community Action",
            "image": "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=1200&q=80",
            "summary": "Volunteers organized winter kits and coordinated blanket distribution for homeless families.",
            "status": "completed",
            "completed_on": "2025-11-30",
            "location": "Central Chennai Shelter Network",
            "impact": "410 kits distributed",
            "is_active": True,
        },
        {
            "title": "Government School Notebook Drive",
            "stream": "Education Support",
            "image": "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80",
            "summary": "Collected and distributed notebooks, stationery, and school bags with parent orientation sessions.",
            "status": "completed",
            "completed_on": "2025-10-19",
            "location": "North Chennai Schools Cluster",
            "impact": "920 students supported",
            "is_active": True,
        },
        {
            "title": "Community Health Screening Assistance",
            "stream": "Healthcare Support",
            "image": "https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=1200&q=80",
            "summary": "Teen volunteers managed patient flow and registration support during weekend health camps.",
            "status": "completed",
            "completed_on": "2025-09-14",
            "location": "Perambur PHC Zone",
            "impact": "620 residents assisted",
            "is_active": True,
        },
        {
            "title": "Canal Cleanup and Waste Segregation Drive",
            "stream": "Environment",
            "image": "https://images.unsplash.com/photo-1621451537084-482c73073a0f?auto=format&fit=crop&w=1200&q=80",
            "summary": "Youth teams removed floating waste and led neighborhood waste segregation demonstrations.",
            "status": "completed",
            "completed_on": "2025-08-24",
            "location": "Buckingham Canal Stretch, Chennai",
            "impact": "2.1 tons waste removed",
            "is_active": True,
        },
        {
            "title": "Elder Home Cultural Evening",
            "stream": "Elder Care",
            "image": "https://images.unsplash.com/photo-1516307365426-bea591f05011?auto=format&fit=crop&w=1200&q=80",
            "summary": "Students hosted music and storytelling sessions with elders to improve social engagement.",
            "status": "completed",
            "completed_on": "2025-07-27",
            "location": "Anbu Old Age Home, Chennai",
            "impact": "120 elders engaged",
            "is_active": True,
        },
        {
            "title": "Public Library Volunteer Cataloging Week",
            "stream": "Education Support",
            "image": "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1200&q=80",
            "summary": "Volunteer batches digitized catalog entries and arranged themed reading corners.",
            "status": "completed",
            "completed_on": "2025-06-16",
            "location": "Connemara Public Library, Chennai",
            "impact": "1,450 books processed",
            "is_active": True,
        },
        {
            "title": "Beach Plastic Audit Campaign",
            "stream": "Environment",
            "image": "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=1200&q=80",
            "summary": "Volunteers collected and categorized beach plastic to help municipal planning.",
            "status": "completed",
            "completed_on": "2025-05-18",
            "location": "Marina Beach, Chennai",
            "impact": "18 cleanup teams coordinated",
            "is_active": True,
        },
    ]

    for row in rows:
        VolunteerEvent.objects.get_or_create(
            title=row["title"],
            defaults=row,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_volunteerevent_volunteereventregistration"),
    ]

    operations = [
        migrations.RunPython(seed_more_volunteer_events, migrations.RunPython.noop),
    ]
