# Generated by Django 5.2.11 on 2026-03-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_seed_more_volunteer_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerevent',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='volunteer/events/'),
        ),
    ]
