# Generated by Django 5.2.11 on 2026-03-30 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_sitesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteereventregistration',
            name='mentee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_registrations', to='core.mentee'),
        ),
        migrations.AlterField(
            model_name='volunteereventregistration',
            name='submitted_by_role',
            field=models.CharField(choices=[('mentee', 'Mentee'), ('mentor', 'Mentor'), ('admin', 'Admin'), ('guest', 'Guest')], default='mentee', max_length=20),
        ),
    ]
