# Generated by Django 5.2.11 on 2026-03-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_volunteereventregistration_mentee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentee',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='mentee',
            name='country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='mentee',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mentee',
            name='school_or_college',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mentee',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
