# Generated by Django 5.2.11 on 2026-04-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_mentor_city_mentor_country_mentor_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoridentityverification',
            name='professional_certificate_document',
            field=models.FileField(blank=True, null=True, upload_to='mentor_verification/professional_certificate/'),
        ),
    ]
