# Generated by Django 5.2.11 on 2026-04-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_mentoridentityverification_professional_certificate_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerevent",
            name="completion_brief",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="volunteerevent",
            name="gallery_images",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="volunteerevent",
            name="joined_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
