# Generated by Django 5.2.11 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_contactotprequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matchrecommendation",
            name="source",
            field=models.CharField(
                choices=[
                    ("seed", "Seed"),
                    ("rules", "Rules"),
                    ("openai", "OpenAI"),
                    ("openrouter", "OpenRouter"),
                    ("manual", "Manual"),
                ],
                default="seed",
                max_length=20,
            ),
        ),
    ]
