# Generated by Django 5.2.11 on 2026-04-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_matchrecommendation_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerevent',
            name='budget_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
